title: EAE Data Sciences Blog
author: Andrew Kiekhaefer
email: kiekhaeferandrewp@johndeere.com
description: > # this means to ignore newlines until "baseurl:"
  Blog regarding common topics in data enigineering, statistics, optimization and machine learning
theme: minima

# social links
github_username:  ak97126 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
